export const twIndexStyles = {
    safeArea:  "flex-1 bg-black",
    titleRow: "justify-center items-center relative",
    title: "text-center text-white text-2xl font-bold",
    iosPickerOverlay: "absolute left-2.5 right-2.5 z-50 bg-black rounded-lg items-center",
    dismissOverlay: "absolute top-0 bottom-0 left-0 right-0 z-40",
    wrapper: "flex-1 bg-black p-2.5",
    container: "flex-row gap-3 justify-center mt-10",
    displayTasks: "flex-row gap-3 justify-center",
    textInput: "justify-center h-11 border-1 border-gray-800 bg-gray-800 rounded-lg px-2.5 text-white",
    taskInput: "flex-3 justify-center",
    dateInput: "flex-0.6 justify-center items-center",
    iconButton: "flex-0 h-11 aspect-[0.88] rounded-lg justify-center items-center bg-white",
    listHeader: "flex-row pb-1 text-base",
    headerText: "text-white font-bold text-base mb-2.5",
    taskRow: "flex-row py-2 border-b-0.25 border-b-gray-900 items-center",
    taskText: "text-white flex-3",
    deadlineText: "flex-1 text-gray-300",
    doneText: "text-gray-500 line-through",
    actionButton: "flex-0 h-11 aspect-[0.88] rounded-lg justify-center items-center bg-black",
    marginBottom: "mb-3.75",
}